export const environment = {
    REST_API_SERVER: 'http://localhost:8080/',
    PRODUCTS: 'product',
    PRODUCT_ORDER: 'product-order',
    PRODUCTS_BY_CATEGORY: 'product/category',
    BUILDS: 'build',
    BUILD_ORDER: 'build-order',
    VIRTUAL_BUILD_ORDER: 'virtual-build-order',
    BUILDS_BY_FILTER: 'build/by-filter',
    SELL_BUILD: 'build/sell-pc-build',
    SOLD_BUILDS: 'statistics/get-sold-builds',
    CATEGORIES: 'categories',
    CPU: 'cpu',
    CPU_BY_SOCKET: 'cpu/by-socket',
    COOLER: 'cooler',
    MOTHERBOARD: 'motherboard',
    MOTHERBOARD_BY_SOCKET: 'motherboard/by-socket',
    MOTHERBOARD_BY_RAM_TYPE: 'motherboard/by-ram-type',
    MOTHERBOARD_BY_SOCKET_AND_RAM_TYPE: 'motherboard/by-socket-and-ram-type',
    MEMORY: 'memory',
    MEMORY_BY_TYPE: 'memory/by-type',
    STORAGE: 'storage',
    GPU: 'gpu',
    PSU: 'psu',
    CASE: 'case'
}